# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Justin C. Bagley - Ecological & Evolutionary Genetics
author :
  name : Justin C. Bagley
  email : jcbagley@vcu.edu
  github : justincbagley
  twitter : justincbagley
  feedburner : nil


theme: jekyll-theme-minimal
